---

- name: Check if npx is in PATH
  ansible.builtin.command: "which npx"
  register: npx_path
  ignore_errors: true

- name: Display message if npx is not found
  debug:
    msg: "npx is not installed or not in PATH"
  when: npx_path.rc != 0
  ignore_errors: false