---
# on execution, overwrite project_name with
#
# ansible-playbook my_playbook.yml --extra-vars "project_name=my_project_name"
# 
# Project name is transformed across multiple tasks, 
# so you need to change this to your preference.
# Underscore as separator preferred.

- name: Provision a Grav Local Project with Hosts and Composer
  hosts: localhost
  connection: local
  vars:
    project_name: grav_setup
    project_directory:
    license: MIT
    php_version: 8.4
    # gitignore: laravel
    # Reminder: Cross-check listed modules against PPA of ondrej
    php_modules:
      - curl
      - ctype
      # - dom > installed as xml
      - gd
      - fpm
      # - json > use fpm
      - mbstring
      # - openssl built in, check with php -i | grep -i openssl   
      # - session built in
      - simplexml
      - xml
      - apcu
      - opcache
      - yaml
    node_global_modules: []
    node_modules: []
    node_dev_modules: []
    # for php-fpm and apache user overwrite
    dev_user: ghost
    dev_group: ghost
    # composer dependencies, exec sequentially
    composer_packages:
    # Grav plugins
    grav_plugins:
  roles:
    - common
    - php
    - php-fpm
    - npm
    - composer
    - gravcms
    - apache
    - hosts
