- name: Install Node Version Manager and Node in system
  hosts: localhost
  connection: local
  roles:
    - nvm
  vars:
    modular_config: true

# Current state of this playbook only installs nvm
# But does not set and activate node.
