- name: Install PHP on system using the Ondrej Repository
  hosts: localhost
  connection: local
  roles:
    - php
  vars:
    modular_config: true
    php_version: 8.4
    # For the modules, only use the keywords. The task must handle the actual naming.
    php_modules: []

# TODO:
# - An install method that does not use Ondrej
# - php.ini modifier and template

