- name: Install PHP on system using the Ondrej Repository
  hosts: localhost
  connection: local
  roles:
    - php
  vars:
    modular_config: true
    php_version: 8.4
    # For the modules, only use the keywords. The task must handle the actual naming.
    php_modules: []

# TODO:
# - An install method that does not use Ondrej
# - php.ini modifier and template
# - Skip only if declared PHP version exists on system (must parse php --version output).

# NOTE:
# - So you don't need to modify php.ini exactly.
#   Both .htaccess (apache) and .conf (nginx) provides ways to do this per install.
#   Deal with the php values needed this way instead when doing the 
#   Dev playbooks.