- name: Install Node Version Manager and Node in system
  hosts: localhost
  connection: local
  roles:
    - npm
  vars:
    modular_config: true
    node_version: node
    node_modules: []
    project_name: null
    project_directory_name: null
    project_directory: null


# This is a playbook to setup node-exclusive settings
# And functionality in node.
# Install tasks for an interpreter (node/python)
# Should be joined with the version manager
# Responsible for it.
# Ideally functionality in the interpreter playbook
# Should cohere with the functionality in the
# Version manager playbook.