- name: Setup Node in System
  hosts: localhost
  connection: local
  roles:
    - common
    - npm
  vars:
    modular_config: true
    node_version: "node"
    node_modules: []
    node_dev_modules: []
    node_global_modules: []
    # transform project name in the common role for dir name
    project_name: null
    # must be absolute path, without project_dir_name
    project_directory: null
    project_mode: "development"


# This is a playbook to setup node-exclusive settings
# And functionality in node.
# Install tasks for an interpreter (node/python)
# Should be joined with the version manager
# Responsible for it.
# Ideally functionality in the interpreter playbook
# Should cohere with the functionality in the
# Version manager playbook.