---
# Checks
- name: Check if Composer is in PATH
  ansible.builtin.command: "which composer"
  register: composer_path

- name: Install Composer globally
  when: composer_path.rc != 0
  become: true
  become_method: sudo
  ansible.builtin.script: "files/install-composer.sh {{ composer_version | default('') }}"