- name: Update apt
  become: true
  become_method: sudo
  ansible.builtin.apt:
    update_cache: yes

- name: Install python build dependencies
  become: true
  become_method: sudo
  ansible.builtin.apt:
    pkg:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - git
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present

- name: Install pyenv using the recommended runner
  become: false
  shell: "curl -fsSL https://pyenv.run | bash"

# TODO: Add pyenv shims for shells, but first create a shell rc management playbook.
# https://github.com/pyenv/pyenv/?tab=readme-ov-file#b-set-up-your-shell-environment-for-pyenv

# Below is temporary, improve it.
# TODO: Add check that the .config-zsh-custom was run on system
# Maybe add an empty hidden file in root as a validation?
- name: Add pyenv shell config to config folder in zsh.
  become: false
  ansible.builtin.template:
    src: templates/pyenv.zsh.j2
    dest: "{{ ansible_user_dir }}/.config/shells/zsh/config/pyenv.zsh"
    mode: '0644'