---
# Checks

- name: Check if PHP is in PATH
  ansible.builtin.command: "which php"
  register: php_path
  ignore_errors: true

- name: Display message if PHP is not found
  when: php_path.rc != 0
  debug:
    msg: "PHP is not installed or not in PATH"
  ignore_errors: true

- name: Install Ondrej Repository
  when: php_path.rc != 0
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP
  when: php_path.rc != 0
  ansible.builtin.apt:
    name: "php{{ php_vers }}"

# - name: Obtain PHP version
#   ansible.builtin.shell: "php -v | head -n 1 | cut -d \" \" -f 2 | cut -f1-2 -d\".\""
#   register: php_vers

