---
# 2025-01-21, 06:06:55 PM
# By adding an install procedure
# This task assumes the version
# to be explicitly declared in a 
# playbook var.

# Checks

- name: Check if PHP is in PATH
  ansible.builtin.command: "which php"
  register: php_path
  ignore_errors: true

- name: Display message if PHP is not found
  when: php_path.rc != 0
  debug:
    msg: "PHP is not installed or not in PATH"
  ignore_errors: true

# Personal note: Launchpad may be blocked on
# network. Might require VPN.
- name: Install Ondrej Repository
  when: php_path.rc != 0
  become: true
  become_method: sudo
  shell: "add-apt-repository ppa:ondrej/php -y"

- name: Update apt
  when: php_path.rc != 0
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: Install PHP
  when: php_path.rc != 0
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name: "php{{ php_version }}"
    state: present

- name: Install PHP Modules
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name: "php{{ php_version }}-{{ item }}"
    state: present
  loop: "{{ php_modules }}"