---
# Checks

- name: Check if PHP is in PATH
  ansible.builtin.command: "which php"
  register: php_path
  ignore_errors: true

- name: Display message if PHP is not found
  debug:
    msg: "PHP is not installed or not in PATH"
  when: php_path.rc != 0
  ignore_errors: false

- name: Obtain PHP version
  ansible.builtin.shell: "php -v | head -n 1 | cut -d \" \" -f 2 | cut -f1-2 -d\".\""
  register: php_vers
  ignore_errors: true
