---
# on execution, overwrite project_name with
#
# ansible-playbook my_playbook.yml --extra-vars "project_name=my_project_name"
# 
# Project name is transformed across multiple tasks, 
# so you need to change this to your preference.
# Underscore as separator preferred.

- name: Provision a Laravel Local Development with Mariadb, Apache, and PHP-FPM
  hosts: localhost
  connection: local
  vars:
    project_name: laravel_setup_test
    license: MIT
    gitignore: laravel
    require_breeze: false
    breeze_ui: blade
    dev_user: ghost
    dev_group: ghost
    # suffix_db must be alphanumeric
    suffix_db: laravel
    # suffix_user must be alphanumeric
    suffix_user: dbadmin
  roles:
    - common
    - php
    - php-fpm
    - npm
    - composer
    - mariadb
    - laravel
    - git
    - apache
    - hosts

