---
- name: Provision a Laravel Local Development with Mariadb
  hosts: localhost
  connection: local
  vars:
    - db_host: 127.0.0.1
    - db_port: 3306
    - license: MIT
    - gitignore: laravel
    - require_breeze: true
    - breeze_ui: blade
  vars_prompt:
    - name: project_name
      prompt: "Enter the name of your project (use underscore for space, lowercase preferred)"
      private: no
  roles:
    - common
    - php
    - npx
    - npm
    - composer
    - mariadb
    - apache
    - hosts
    - laravel
    - envfile
    - git

