---
# on execution, overwrite project_name with
#
# ansible-playbook my_playbook.yml --extra-vars "project_name=my_project_name"
# 
# Project name is transformed across multiple tasks, 
# so you need to change this to your preference.
# Underscore as separator preferred.

- name: Provision a wordpress instance with wp-cli, mariadb, and apache2
  hosts: localhost
  connection: local
  vars:
    - project_name: wpcli_setup
    - license: MIT
    - gitignore: WordPress
    - dev_user: ghost
    - dev_group: ghost
    # suffix_db must be alphanumeric
    - suffix_db: wp2342
    # suffix_user must be alphanumeric
    - suffix_user: dbacnt
  roles:
    - common
    - php
    - php-fpm
    - npm
    - mariadb
    - wp-cli
    - git
    - apache
    - hosts

